services:
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok_tunnel_service
    ports:
      - "4040:4040" 
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTH_TOKEN}
    command:
      - "http"
      - "host.docker.internal:3005"
      - "--log=stdout"