import { config } from "dotenv";

config();

export const {
  NODE_ENV,
  PORT,
  DB_URI,
  JWT_SECRET,
  JWT_EXPIRES_IN,
  AWS_BUCKET_NAME,
  AWS_SECRET_ACCESS_KEY,
  AWS_REGION,
  AWS_ACCESS_KEY_ID,
  PORT_AUTH_SERVICE,
  VNP_TMNCODE,
  VNP_HASHSECRET,
  VNP_URL,
  VNP_RETURN_URL,
  VNP_IPN_URL,
  PORT_OF_NGROK,
  FRONTEND_URL,
  NGROK_AUTH_TOKEN,
  RABBITMQ_URL,
  NOTIFICATION_EXCHANGE,
  NOTIFICATION_QUEUE,
  SERVICE_NAME,
  UPDATE_SEAT_EXCHANGE,
  TRIP_SERVICE_ROUTING_KEY,
  URL_AUTH_SERVICE
} = process.env;
