apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  DB_URI_SECRET: mongodb+srv://chautinh05122_db_user:Chautinh0512%40@cluster0.s0rshdf.mongodb.net/bus_book_tickets?retryWrites=true&w=majority&appName=Cluster0
  JWT_SECRET: smart_bus_doAnTotNghiep2025
  JWT_REFRESH_SECRET: smart_bus_refresh_doAnTotNghiep2025