# booking-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: booking-secret
type: Opaque
stringData:
  DB_URI_SECRET: mongodb+srv://chautinh05122_db_user:Chautinh0512%40@cluster0.s0rshdf.mongodb.net/bus_book_tickets?retryWrites=true&w=majority&appName=cluster0
  
  JWT_SECRET: smart_bus_doAnTotNghiep2025
  
  VNP_TMNCODE: OB1Z73C7
  VNP_HASHSECRET: F3BZWDWM3GLAPIU8V26LZ0HYRT7JMKG7