# --- DEPLOYMENT BOOKING SERVICE ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service-deployment
  labels:
    app: booking-service
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
      - name: booking-service-container
        image: asia-southeast1-docker.pkg.dev/smartbusproject-480408/smartbus-repo/booking-service:v8.5
        ports:
        - containerPort: 3005 
        
        # BỎ HOÀN TOÀN envFrom
        env:
        # A. Ghi đè Biến Localhost bằng ConfigMap
        - name: REDIS_URL # Biến mà code đang tìm kiếm (ghi đè localhost:6379)
          valueFrom:
            configMapKeyRef:
              name: smartbus-config
              key: REDIS_URL_PROD 
        - name: RABBITMQ_URL # Biến mà code đang tìm kiếm (ghi đè localhost:5672)
          valueFrom:
            configMapKeyRef:
              name: smartbus-config
              key: RABBITMQ_URL_PROD
        - name: URL_BOOKING_SERVICE
          valueFrom:
            configMapKeyRef:
              name: smartbus-config
              key: URL_BOOKING_SERVICE
        - name: URL_TRIP_SERVICE
          valueFrom:
            configMapKeyRef:
              name: smartbus-config
              key: URL_TRIP_SERVICE
        - name: URL_AUTH_SERVICE
          valueFrom:
            configMapKeyRef:
              name: smartbus-config
              key: URL_AUTH_SERVICE
        # B. Biến Nhạy cảm từ Secret
        - name: DB_URI 
          valueFrom:
            secretKeyRef:
              name: booking-secret
              key: DB_URI_SECRET
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: booking-secret
              key: JWT_SECRET
        - name: VNP_TMNCODE
          valueFrom:
            secretKeyRef:
              name: booking-secret
              key: VNP_TMNCODE
        - name: VNP_HASHSECRET
          valueFrom:
            secretKeyRef:
              name: booking-secret
              key: VNP_HASHSECRET

        # C. Biến Logic và Cấu hình (Từ ConfigMap)
        - name: NOTIFICATION_EXCHANGE
          valueFrom:
            configMapKeyRef:
              name: smartbus-config
              key: NOTIFICATION_EXCHANGE
        - name: NOTIFICATION_QUEUE
          valueFrom:
            configMapKeyRef:
              name: smartbus-config
              key: EMAIL_NOTIFICATION_QUEUE # Lấy tên queue
        - name: UPDATE_SEAT_EXCHANGE
          valueFrom:
            configMapKeyRef:
              name: smartbus-config
              key: UPDATE_SEAT_EXCHANGE
        - name: TRIP_SERVICE_ROUTING_KEY
          valueFrom:
            configMapKeyRef:
              name: smartbus-config
              key: TRIP_SERVICE_ROUTING_KEY

        # Các URL VNPAY không nhạy cảm
        - name: VNP_URL
          valueFrom:
            configMapKeyRef:
              name: smartbus-config
              key: VNP_URL
        - name: VNP_RETURN_URL
          valueFrom:
            configMapKeyRef:
              name: smartbus-config
              key: VNP_RETURN_URL
        - name: VNP_IPN_URL
          valueFrom:
            configMapKeyRef:
              name: smartbus-config
              key: VNP_IPN_URL
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: smartbus-config
              key: FRONTEND_URL
              
        # D. Biến Cố định (Gán trực tiếp)
        - name: PORT
          value: "3005"
        - name: SERVICE_NAME
          value: "BOOKING-SERVICE"
        - name: NODE_ENV
          value: "production" 
          
---

# --- SERVICE --- (ClusterIP: Chỉ nội bộ)
apiVersion: v1
kind: Service
metadata:
  name: booking-service
spec:
  selector:
    app: booking-service
  ports:
  - protocol: TCP
    port: 3005
    targetPort: 3005
  type: ClusterIP