# cluster-issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Thay thế bằng email của bạn
    email: vantien12122002@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Nơi lưu trữ khóa riêng của Issuer
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx