# notification-secret.yaml (Sử dụng stringData)
apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
type: Opaque
stringData:
  DB_URI_SECRET: mongodb+srv://chautinh05122_db_user:Chautinh0512%40@cluster0.s0rshdf.mongodb.net/bus_book_tickets?retryWrites=true&w=majority&appName=Cluster0
  SMTP_PASS_SECRET: lbit wqrc swvf sysj
  SMTP_USER_SECRET: vantien12122002@gmail.com