# trip-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: trip-secret
type: Opaque
stringData:
  # Chuỗi kết nối MongoDB Atlas (Rất nhạy cảm)
  MONGO_URI_ATLAS_SECRET: mongodb+srv://chautinh05122_db_user:Chautinh0512%40@cluster0.s0rshdf.mongodb.net/bus_book_tickets?retryWrites=true&w=majority&appName=Cluster0