import dotenv from "dotenv";
dotenv.config();

export const {
  NODE_ENV,
  PORT,
  DB_URI,
  JWT_SECRET,
  JWT_REFRESH_SECRET,
  JWT_REFRESH_EXPIRES_IN,
  JWT_EXPIRES_IN,
  REDIS_URL,
  RABBITMQ_URL,
  NOTIFICATION_EXCHANGE,
  OTP_EXPIRY_SECONDS,
  SESSION_EXPIRY_SECONDS,
  SERVICE_NAME,
  HISTORY_SEARCH_EXCHANGE,
  SEARCH_HISTORY_QUEUE,
  HISTORY_SEARCH_ROUTING_KEY,
  SMTP_USER,
  SMTP_PASS,
  SMTP_HOST,
  SMTP_PORT,
} = process.env;
