import dotenv from "dotenv";
dotenv.config();

export const {
  NODE_ENV,
  PORT,
  MONGO_URI_LOCAL,
  MONGO_URI_ATLAS,
  EUREKA_HOST,
  EUREKA_PORT,
  SERVICE_NAME,
  RABBITMQ_URL,
  HISTORY_SEARCH_EXCHANGE,
  NOTIFICATION_QUEUE,
  HISTORY_SEARCH_ROUTING_KEY,
  UPDATE_SEAT_EXCHANGE,
  TRIP_SERVICE_QUEUE,
  TRIP_SERVICE_ROUTING_KEY,
} = process.env;
